name: mvsnerf
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h33c6efd_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - p7zip=16.02=h9c3ff4c_1001
  - pip=24.3.1=pyh8b19718_0
  - python=3.8.20=h4a871b0_2_cpython
  - readline=8.3=h853b02a_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - configargparse==1.7.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - future==1.0.0
      - google-auth==2.47.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - idna==3.11
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - inplace-abn==1.1.0
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.10
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - lpips==0.1.4
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - multidict==6.1.0
      - networkx==3.1
      - numpy==1.24.4
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.0.3
      - pillow==9.5.0
      - propcache==0.2.0
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydeprecate==0.3.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.3.5
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==5.4.1
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-image==0.21.0
      - scipy==1.10.1
      - six==1.17.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - test-tube==0.7.5
      - tifffile==2023.7.10
      - torch==1.10.1+cu113
      - torchaudio==0.10.1+cu113
      - torchmetrics==0.7.3
      - torchvision==0.11.2+cu113
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - tzdata==2025.3
      - urllib3==2.2.3
      - warmup-scheduler==0.3
      - werkzeug==3.0.6
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /ibex/user/yaoz0b/conda-environments/mvsnerf
